### ISSUE TITLE
Missing filter menu

### ISSUE THREAD

**Issue by braultatgithub** [redhat-cip/dci-ui#76]
![screen shot 2018-11-05 at 7 26 33 pm](https://user-images.githubusercontent.com/20091420/48018409-119dc700-e131-11e8-9b69-78290b33bd68.png)

**Comment by guillaumevincent** [comment]
Hello,
normally it should be fixed in the new version of DCI.
Tell me if you encounter again the problem

I close

**Comment by pkchavva** [comment]
Hi,
Congrats on the new UI ,it looks really good :)

I am still having the same filter team issue. I think this is an access privilege issue.

However when I use the epmtest username I can access the "filter by team" and other options.

**Comment by guillaumevincent** [comment]
ack I will take a look at this issue
Thank you for extra details

**Comment by braultatgithub** [comment]
Trying to bring closure to this issue, although this is marked as closed.
Issue still exists as before UI update.
Any suggestion.

**Comment by guillaumevincent** [comment]
Indeed it's a permission problem, read only user (SSO) are not able to list teams
I will open an issue on the dci-control-server side

**Comment by pkchavva** [comment]
Hi,

I have the same issue as well that I am unable to see the list of teams but I can see the list by team filter.

![screenshot-www distributed-ci io-2018 12 11-09-02-55](https://user-images.githubusercontent.com/25849453/49805689-c4120c80-fd23-11e8-8b73-c906ffa0e7fc.png)


Best,
Pavan.

**Comment by guillaumevincent** [comment]
Hi @pkchavva,
I created an issue on the control-server https://github.com/redhat-cip/dci-control-server/issues/75
Thank you
